inherit_from:
  - .rubocop_enabled.yml
  - .rubocop_disabled.yml

# Common configuration.
AllCops:
  Exclude:
    - 'tcc.gemspec'
  TargetRubyVersion: 2.2

Style/MultilineOperationIndentation:
  EnforcedStyle: indented
  SupportedStyles:
    - aligned
    - indented

# Indentation of `when`.
Style/CaseIndentation:
  EnforcedStyle: case
  SupportedStyles:
    - case
    - end
  IndentOneStep: true

Style/PercentLiteralDelimiters:
  # Specify the default preferred delimiter for all types with the 'default' key
  # Override individual delimiters (even with default specified) by specifying
  # an individual key
  PreferredDelimiters:
    default: ()
    '%r': '{}'
    '%i': '()'
    '%I': '()'
    '%w': '()'
    '%W': '()'

Style/SignalException:
  EnforcedStyle: semantic
  SupportedStyles:
    - only_raise
    - only_fail
    - semantic

##################### Metrics ##################################

Metrics/LineLength:
  Max: 100
  AllowURI: true
  URISchemes:
    - http
    - https

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false
